### ISSUE TITLE
CMake minimum version

### ISSUE THREAD

**Issue by johnaparker** [SSAGESLabs/openmm-dlext#14]
This line seems to cause issues with configuring in CMake 3.15:
https://github.com/SSAGESLabs/openmm-dlext/blob/2ec5ff935cdd8d2adfca19a0713691f862b58a33/cmake/Modules/FindOpenMM.cmake#L66

**Comment by pabloferz** [comment]
Do you have a log? If not, I can try to build with that CMake version.

**Comment by johnaparker** [comment]
Here's the relevant error message. I confirmed it works with CMake 3.16+, so one option is to update the minimum version from 3.13 to 3.16
```
CMake Error at cmake/Modules/FindOpenMM.cmake:66 (target_include_directories):
  target_include_directories called with non-compilable target type
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Found CUDA: /software/cuda-10.1-el7-x86_64 (found version "10.1")
CMake Error at cmake/Modules/FindOpenMM.cmake:85 (target_compile_definitions):
  target_compile_definitions called with non-compilable target type
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


CMake Error at cmake/Modules/FindOpenMM.cmake:86 (target_include_directories):
  target_include_directories called with non-compilable target type
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


CMake Error at cmake/Modules/FindOpenMM.cmake:89 (target_include_directories):
  target_include_directories called with non-compilable target type
Call Stack (most recent call first):
```

**Comment by pabloferz** [comment]
Ok, the code I wrote in `FindOpenMM.cmake` seems to be fine, but there was an issue in CMake pre 3.16 https://gitlab.kitware.com/cmake/cmake/-/issues/19434. So, setting the minimum CMake version to 3.16 seems to be the correct solution.
